package pkg

type CommandID uint32

const (
	SGIP_REQUEST_MIN, SGIP_RESPONSE_MIN CommandID = iota, 0x80000000 + iota
	SGIP_BIND, SGIP_BIND_RESP
	SGIP_UNBIND, SGIP_UNBIND_RESP
	SGIP_SUBMIT, SGIP_SUBMIT_RESP
	SGIP_DELIVER, SGIP_DELIVER_RESP
	SGIP_REPORT, SGIP_REPORT_RESP

	SGIP_ADDSP, SGIP_ADDSP_RESP
	SGIP_MODIFYSP, SGIP_MODIFYSP_RESP
	SGIP_DELETESP, SGIP_DELETESP_RESP
	SGIP_QUERYROUTE, SGIP_QUERYROUTE_RESP
	SGIP_ADDTELESEG, SGIP_ADDTELESEG_RESP
	SGIP_MODIFYTELESEG, SGIP_MODIFYTELESEG_RESP
	SGIP_DELETETELESEG, SGIP_DELETETELESEG_RESP
	SGIP_ADDSMG, SGIP_ADDSMG_RESP
	SGIP_MODIFYSMG, SGIP_MODIFYSMG_RESP
	SGIP_DELETESMG, SGIP_DELETESMG_RESP
	SGIP_CHECKUSER, SGIP_CHECKUSER_RESP
	SGIP_USERRPT, SGIP_USERRPT_RESP
	SGIP_TRACE, SGIP_TRACE_RESP

	SGIP_REQUEST_MAX, SGIP_RESPONSE_MAX
)

func (id CommandID) String() string {
	if id <= SGIP_REPORT && id > SGIP_REQUEST_MIN {
		return []string{
			"SGIP_BIND",
			"SGIP_UNBIND",
			"SGIP_SUBMIT",
			"SGIP_DELIVER",
			"SGIP_REPORT",
		}[id-1]
	} else if id < SGIP_REQUEST_MAX {
		return []string{
			"SGIP_ADDSP",
			"SGIP_MODIFYSP",
			"SGIP_DELETESP",
			"SGIP_QUERYROUTE",
			"SGIP_ADDTELESEG",
			"SGIP_MODIFYTELESEG",
			"SGIP_DELETETELESEG",
			"SGIP_ADDSMG",
		}[id-0x00000006]
	}

	if id <= SGIP_REPORT_RESP && id > SGIP_RESPONSE_MIN {
		return []string{
			"SGIP_BIND_RESP",
			"SGIP_UNBIND_RESP",
			"SGIP_SUBMIT_RESP",
			"SGIP_DELIVER_RESP",
			"SGIP_REPORT_RESP",
		}[id-0x80000001]
	} else if id < SGIP_RESPONSE_MAX {
		return []string{
			"SGIP_ADDSP_RESP",
			"SGIP_MODIFYSP_RESP",
			"SGIP_DELETESP_RESP",
			"SGIP_QUERYROUTE_RESP",
			"SGIP_ADDTELESEG_RESP",
			"SGIP_MODIFYTELESEG_RESP",
			"SGIP_DELETETELESEG_RESP",
			"SGIP_ADDSMG_RESP",
		}[id-0x80000006]
	}
	return "unknown"
}
